#!/bin/bash
# This script creates a new user on the local system.

userfile=/newuser.csv
username=$(cat /newuser.csv)
password="Manchester123"


# if statement to check if user already exists in the passwd directory
if [[if -u ${username} &>/dev/null ]] ; then
echo "${username} already exist and account will not be created"
else 
for user in $username
do
echo "Creating user account for user '${user}'."
useradd $user -m -g developers -s /bin/bash
echo $password | sudo passwd --stdin $user && 

mkdir /home/${user}/.ssh && sudo chown $user /home/${user}/.ssh/ && sudo chmod 700 /home/$user/.ssh/ 
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCinowUjZqwDtILUe6lehhGc6p6WHVzW3wt8tjTk6dSpjL5ovPRQo5Agn1vdS+L4dqX55B+gI42UnHh96GYjqrbwOlnupshgZDKE8qJ2tPcTsHA/5A6c0JSuejMTevzDMcbq/gOCyeIsa5ujp6AuxMyqqYD1i9BTErRjF6ROy82JxS9qgwvfImcFTvG2D9zxYdOstpb6871UT8+rr8GWX0uf9riaSYDKWth0x4V7rHpfipWwNFnmbcl1dxTkgzyAG15UA1ncXF37YHxUMG9YzsSy2lySrKad4lIHZIkcqr8iPeFF9Hq7XA2YowJR7u+3YtdocjmWXO/IqOq09n9cGfn dinul@macbook-pro.local" >> /home/${user}/.ssh/id_rsa.pub &&  sudo chown $user /home/${user}/.ssh/id_rsa.pub && sudo chmod 644 /home/${user}/.ssh/id_rsa.pub && 
cat /home/${user}/.ssh/id_rsa.pub >> /home/${user}/.ssh/authorized_keys && sudo chown $user /home/${user}/.ssh/authorized_keys && sudo chmod 600 /home/${user}/.ssh/authorized_keys

echo "-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAop6MFI2asA7SC1HupXoYRnOqelh1c1t8LfLY05OnUqYy+aLz
0UKOQIJ9b3Uvi+Hal+eQfoCONlJx4fehmI6q28DpZ7qbIYGQyhPKidrT3E7BwP+Q
OnNCUrnozE3r8wzHG6v4DgsniLGubo6egLsTMqqmA9YvQUxK0YxekTsvNicUvaoM
L3yJnBU7xtg/c8WHTrLaW+vO9VE/Pq6/Bll9Ln/a4mkmAylrYdMeFe6x6X4qVsDR
Z5m3JdXcU5IM8gBteVANZ3Fxd+2B8VDBvWM7EstpckqymneJSB2SJHKq/Ij3hRfR
6u1wNmKMCUe7vt2LXaHI5llzvyKjqtPZ/XBn5wIDAQABAoIBAQCP1y/OykZGboWK
L8mooyuvvYXQvEf/Zq+bsQ/rbdJ1/75dI68IrRdIpmOvX/dTgs4oyVH9I1cnY5uK
JdDRMXid8rBB6URoycM5i3H+qAn3983YGfYITYUfyYPKmy4WiXng1ycNvP4WIhxJ
fGtlMJRVn65C/IRF/Oa9Ha1URwaGnXfkkzM6FBvIPfKvZKcT/7bnXr4XnLwTso14
8BFqSqkKBTIrUGTxAIo8YrVwqaBmAaNeNz2QJjn2EL9c8qaZcaQC21fIVbljlMq9
5M0jnfhqU/2Ly0rDEok2gytsrXBXQI1pfHTM1MVVcJHZ4TrBevCXDgsw7P7Rq2Ks
7PrknFG5AoGBANDeDSPqz1k2Qct2tQBMJoC7ED3Foz57LYDqiP2Q9ih6sRqMJJ+K
28PAPKqyxCRa2XdCpiv6YCOHLcnn4iIIRFcYMrwQlcqfHeHrbcd9BJI9+9ryJ+5y
EOg1IA4ZbgXatcw3JXwnomKLgxhRJX3raA1kVlrITwJrIdrnC46No739AoGBAMdQ
0PGW6+YoAD/v3lN8/+Yb2Bx/1j/KxXm6/QzqcBVQdxggu4obao/Ym9o6pvJn9kyv
rZX6K/qToFL6MkaQwcqEN4rdkzA0oqQGgcTfHeM7zXEdzDCD7uWtzSDW2KfZdBPe
JvuuTzwZFTMirXHXO1A49IKkzaWJkfIzPkOhedCzAoGBAMB3jfZF/vH/XFvINHxk
r6o6NnolsAr4aPL9rGS0exDMFn0XHPxjcaWNdJn7h2DU0sXiBcxKuOKkQ15lrmyb
35W+N6ozQkTnoRq43n1QR7EXKwkT0hYYyFmh8rrrVgZRBut6+bDRuQJD+vaieADz
tvt4NVcMdDoPTLAx7eVbwcJlAoGAWbL/NZqMM5pQ8nVLAxvANpjVW44Up8TjtnL2
qzdeldkOn+crP24zOOVsznuS4ojzCXQOlO5vmGeTwYQj2CoRbMiwDmjFcu5dO6BK
CoW296rUPFICsNrPSsI7DMpj2rY8TSyvMpkxw4QuTEMQ96i7YtEfCSSOAC+3ZN62
6Mzk+40CgYBR7rhB3uOtih8JPYkmhwj5FE374MlXCtR5k1ennbQWwCxzs3FiWGqq
i1acdxb4+TYC+6Lp0+DoA8TfhZVB2KkmTRcue/1At9m9EV3oqppaBgcmalFrWooJ
t8L8Si+a5ti2T6KtPAQAjNXW/DM17eaaA5oJJK05YaEH/aHUQftTZA==
-----END RSA PRIVATE KEY-----" >> /home/${user}/.ssh/id_rsa && sudo chown $user /home/$user/.ssh/id_rsa && sudo chmod 600 /home/${user}/.ssh/id_rsa



done

fi

